modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL=""
license="All rights reserved"

[[mods]]
    modId="thutbot"
    version="${file.jarVersion}"
    displayName="Server Side Bot for testing stuff"
    authors="Thutmose"
    description='''
    ThutBot does things.
    '''
    
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="version_mc"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="pokecube"
    mandatory=true
    versionRange="version_pokecube"
    ordering="NONE"
    side="BOTH"